# Generated by Django 5.0.6 on 2024-06-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('effect', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('move_type', models.CharField(max_length=50)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField()),
                ('effect', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sprite_url', models.URLField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('level', models.IntegerField(default=100)),
                ('ev_hp', models.IntegerField(default=0)),
                ('ev_attack', models.IntegerField(default=0)),
                ('ev_defense', models.IntegerField(default=0)),
                ('ev_sp_attack', models.IntegerField(default=0)),
                ('ev_sp_defense', models.IntegerField(default=0)),
                ('ev_speed', models.IntegerField(default=0)),
                ('iv_hp', models.IntegerField(default=31)),
                ('iv_attack', models.IntegerField(default=31)),
                ('iv_defense', models.IntegerField(default=31)),
                ('iv_sp_attack', models.IntegerField(default=31)),
                ('iv_sp_defense', models.IntegerField(default=31)),
                ('iv_speed', models.IntegerField(default=31)),
                ('abilities', models.ManyToManyField(related_name='pokemons', to='teambuilder.ability')),
                ('items', models.ManyToManyField(related_name='pokemons', to='teambuilder.item')),
                ('moves', models.ManyToManyField(related_name='pokemons', to='teambuilder.move')),
            ],
        ),
    ]
