# Generated by Django 5.0.6 on 2024-06-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0003_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pokemons',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TeamPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambuilder.ability')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambuilder.item')),
                ('moves', models.ManyToManyField(to='teambuilder.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambuilder.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_pokemons', to='teambuilder.team')),
            ],
            options={
                'unique_together': {('team', 'slot')},
            },
        ),
    ]
